USE customer_behavior;
 
 SELECT*FROM customer;
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,SUM(purchase_amount) AS total_revenue 
FROM customer 
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied="Yes" and purchase_amount >=(SELECT AVG(purchase_amount) FROM customer);

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased,round(AVG(review_rating)) AS product_review 
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type,AVG(purchase_amount) 
FROM customer
WHERE shipping_type IN("Express","Standard")
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.
SELECT subscription_status,count(customer_id), 
round(AVG(purchase_amount)) AS avg_spend ,
round(SUM(purchase_amount)) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY avg_spend,total_revenue;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100 * AVG(discount_applied = 'Yes')) AS "discount_rate_%"
FROM customer
GROUP BY item_purchased
ORDER BY "discount_rate_%" DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH  customer_type as(
SELECT customer_id,previous_purchases,
CASE 
    WHEN previous_purchases =1 THEN "New"
    WHEN previous_purchases BETWEEN 2 AND 10 THEN "Returning"
    ELSE "Loyal"
    END AS customer_segment
FROM customer
)

SELECT customer_segment,COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY Customer_segment;

-- Q8. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q9. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;



